package CiTixPackage;

import CiTixWebcam.MyWebcam;
import CiTixFileManager.CiTixDocument;
import CiTixChat.Chatroom;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;

/**
 * CiTix Programme Management System Application
 * @author matjele7@gmail.com
 * @version 1.3.1
 */
public class CiTixPMS extends javax.swing.JFrame {

    Image image;
    String imgUrl;
    Login lg;
    
    //Forms
    Chatroom chat;
    MyWebcam wCam;
    CiTixDocument fls;
    
    /**
     * Creates new form CiTixPMS
     */
    public CiTixPMS() {
        initComponents();
        loginTheme();
        chat = new Chatroom();
        this.wCam = new MyWebcam();
        fls = new CiTixDocument();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pnlImage = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        pnlPrograms = new javax.swing.JPanel();
        cmbxProgrames = new javax.swing.JComboBox<>();
        lblCitixImage = new javax.swing.JLabel();
        lblUserDescription = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 255));
        setLocation(new java.awt.Point(600, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        pnlImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUserName.setText("User Name:");
        lblUserName.setPreferredSize(new java.awt.Dimension(60, 15));

        lblPassword.setText("Password:");

        txtPassword.setText("jPasswordField1");

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addContainerGap())
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPrograms.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbxProgrames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Program", "Chatroom", "Webcam", "Files" }));
        cmbxProgrames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxProgramesActionPerformed(evt);
            }
        });

        lblCitixImage.setText("citix Image");

        javax.swing.GroupLayout pnlProgramsLayout = new javax.swing.GroupLayout(pnlPrograms);
        pnlPrograms.setLayout(pnlProgramsLayout);
        pnlProgramsLayout.setHorizontalGroup(
            pnlProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCitixImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlProgramsLayout.createSequentialGroup()
                .addComponent(cmbxProgrames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        pnlProgramsLayout.setVerticalGroup(
            pnlProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbxProgrames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCitixImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUserDescription.setText("UserDecription");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPrograms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegister)
                        .addGap(5, 5, 5)
                        .addComponent(lblUserDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPrograms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(lblUserDescription)
                    .addComponent(btnClose)
                    .addComponent(btnRegister))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Create an image with a selected path to a specific image
     * @param path string image path
     * @return Image Icon
     */
    public Image createImageIcon(String path) {
        URL imageUrl = getClass().getResource(path);
        if (imageUrl != null) {
            return new ImageIcon(imageUrl).getImage().getScaledInstance(150, 113, Image.SCALE_SMOOTH);
        } else {
            return null;
        }
    }

    /**
     * Create a profile image with a selected user image
     * @param path string profile image path
     * @return profile Image
     */
    public Image createProfileImageIcon(String path) {
        URL imageUrl = getClass().getResource(path);
        if (imageUrl != null) {
            return new ImageIcon(imageUrl).getImage().getScaledInstance(210, 113, Image.SCALE_SMOOTH);
        } else {
            return null;
        }
    }

    /**
     * Demonstrates the design layout of the login System
     */
    public void loginTheme() {
        //Display a CiTix Image
        imgUrl = "Images/cape.jpg";
        image = createImageIcon(imgUrl);
        ImageIcon citixIcon = new ImageIcon(image);
        lblCitixImage.setIcon(citixIcon);
        //Disable controls
        cmbxProgrames.setVisible(false);
        lblCitixImage.setVisible(false);
        lblUserDescription.setVisible(false);
        //Enable controls
        lblPassword.setVisible(true);
        txtUserName.setVisible(true);
        txtPassword.setVisible(true);
        lblCitixImage.setVisible(true);
        btnRegister.setVisible(true);
        //Change Text
        lblUserName.setIcon(null);
        lblUserName.setText("User Name:");
        lblPassword.setText("Password:");
        btnLogin.setText("Log In");
        txtUserName.setText("");
        txtPassword.setText("");
        lblCitixImage.setText("");
        
        this.setTitle("CiTix PMS");
    }

    /**
     * Demonstrates the design layout of the log out system
     */
    public void logoutTheme() {
        //Disable controls
        lblPassword.setVisible(false);
        txtUserName.setVisible(false);
        txtPassword.setVisible(false);
        lblCitixImage.setVisible(false);
        btnRegister.setVisible(false);
        
        //Enable Control
        cmbxProgrames.setVisible(true);

        //Change Text
        //this.setTitle("Loged in : " + txtUserName.getText());
        lblCitixImage.setIcon(null);
        lblCitixImage.setText("");
        lblUserDescription.setText("");
        txtPassword.setText("");
        txtUserName.setText("");
        lblUserName.setText("");
        btnLogin.setText("Log Out");
        

        //Profile Image
        imgUrl = "Images/Female.png";
        Image profileImg = createProfileImageIcon(imgUrl);
        ImageIcon icon = new ImageIcon(profileImg);
        icon.setDescription(txtUserName.getText());
        lblUserName.setIcon(icon);
    }

    /**
     * Models a function to stop running application(s) on log out
     */
    public void stopRunningApp() {
        chat.dispose();
        wCam.dispose();
        fls.dispose();        
    }

    /**
     * Demonstrates the closing event from the current form
     */
//    private void close(){
//        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
//        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
//    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //boolean isValid = false;
        lg = new Login(txtUserName.getText(), txtPassword.getText());

        //Logout condition
        if (btnLogin.getText().equals("Log Out")) {
            stopRunningApp();
            lg.logOut();
            loginTheme();            
        }
        if (lg.logIn() == true) {
            logoutTheme();
            this.setTitle("Logged in User: " + lg.getLogedUser());
            //lblUserDescription.setText("   Logged in User: " + lg.getUserLogName());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        if (showConfirmDialog(null, "Sure you want to close the app?", "App Closing", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cmbxProgramesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxProgramesActionPerformed
        int val = cmbxProgrames.getSelectedIndex();
        switch (val) {
            case 1:
                chat.setDefaultCloseOperation(Chatroom.DISPOSE_ON_CLOSE);
                chat.setLocation(200, 200);
                chat.setVisible(true);
                break;
            case 2:
                wCam.setDefaultCloseOperation(MyWebcam.DISPOSE_ON_CLOSE);
                wCam.setLocation(1110, 200);
                wCam.setVisible(true);
                break;
            case 3:
                fls.setDefaultCloseOperation(CiTixDocument.DISPOSE_ON_CLOSE);
                fls.setLocation(600, 10);
                fls.setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cmbxProgramesActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        FormRegister regFrm = new FormRegister();
        regFrm.setLocation(300, 200);
        regFrm.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CiTixPMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CiTixPMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CiTixPMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CiTixPMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CiTixPMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbxProgrames;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCitixImage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserDescription;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlPrograms;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
